
/**
 * Export `seegno` shared configuration preset.
 */

module.exports = {
  env: {
    es6: true,
    mocha: true,
    node: true
  },
  extends: 'eslint:recommended',
  parser: 'babel-eslint',
  plugins: ['babel', 'sort-class-members'],
  root: true,
  rules: {
    'accessor-pairs': 'error',
    'array-bracket-spacing': 'off',
    'arrow-parens': 'off',
    'arrow-spacing': 'error',
    'babel/arrow-parens': ['error', 'as-needed'],
    'babel/generator-star-spacing': ['error', 'before'],
    'block-scoped-var': 'error',
    'block-spacing': 'off',
    'brace-style': 'off',
    camelcase: 'off',
    'comma-dangle': 'off',
    'comma-spacing': 'off',
    'comma-style': 'off',
    complexity: 'off',
    'computed-property-spacing': 'error',
    'consistent-return': 'off',
    'consistent-this': 'error',
    'constructor-super': 'error',
    curly: 'off',
    'default-case': 'error',
    'dot-location': ['error', 'property'],
    'dot-notation': 'off',
    'eol-last': 'off',
    eqeqeq: ['error', 'smart'],
    'func-names': 'off',
    'func-style': ['error', 'declaration', {
      allowArrowFunctions: true
    }],
    'generator-star-spacing': 'off',
    'id-length': ['error', {
      exceptions: ['_', 'e', 'i']
    }],
    indent: 'off',
    'key-spacing': 'off',
    'keyword-spacing': ['off', {
      overrides: {
        case: {
          after: true
        },
        return: {
          after: true
        },
        throw: {
          after: true
        }
      }
    }],
    'linebreak-style': 'off',
    'lines-around-comment': 'off',
    'max-depth': 'error',
    'max-nested-callbacks': 'off',
    'max-params': ['error', 4],
    'new-cap': 'off',
    'new-parens': 'error',
    'newline-after-var': 'off',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-caller': 'error',
    'no-catch-shadow': 'off',
    'no-class-assign': 'error',
    'no-cond-assign': ['error', 'always'],
    'no-confusing-arrow': 'error',
    'no-const-assign': 'error',
    'no-constant-condition': 'error',
    'no-div-regex': 'error',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'error',
    'no-else-return': 'error',
    'no-empty-label': 'off',
    'no-empty': 'off',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-parens': 'error',
    'no-floating-decimal': 'error',
    'no-implied-eval': 'error',
    'no-inline-comments': 'error',
    'no-iterator': 'error',
    'no-label-var': 'off',
    'no-labels': 'off',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-mixed-requires': 'error',
    'no-mixed-spaces-and-tabs': 'off',
    'no-multi-spaces': 'off',
    'no-multi-str': 'off',
    'no-native-reassign': 'error',
    'no-nested-ternary': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-require': 'error',
    'no-new-wrappers': 'error',
    'no-new': 'error',
    'no-octal-escape': 'error',
    'no-path-concat': 'error',
    'no-process-env': 'error',
    'no-process-exit': 'error',
    'no-proto': 'error',
    'no-restricted-modules': 'error',
    'no-return-assign': 'error',
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow-restricted-names': 'error',
    'no-shadow': 'off',
    'no-spaced-func': 'off',
    'no-sync': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'off',
    'no-underscore-dangle': 'off',
    'no-unexpected-multiline': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-use-before-define': 'error',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-warning-comments': 'off',
    'no-with': 'off',
    'object-curly-spacing': 'off',
    'object-shorthand': 'error',
    'one-var': 'off',
    'operator-assignment': 'error',
    'operator-linebreak': 'off',
    'padded-blocks': 'off',
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    quotes: 'off',
    'quote-props': 'off',
    radix: 'error',
    'require-yield': 'error',
    semi: 'off',
    'semi-spacing': 'off',
    'sort-class-members/sort-class-members': ['error', {
      order: [
        'constructor',
        '[static-methods]',
        '[static-properties]',
        '[properties]',
        '[methods]',
        '[conventional-private-properties]',
        '[conventional-private-methods]',
        '[everything-else]'
      ],
    }],
    'sort-vars': 'error',
    'space-before-blocks': 'off',
    'space-before-function-paren': 'off',
    'space-in-parens': 'off',
    'space-infix-ops': 'off',
    'space-unary-ops': 'off',
    'spaced-comment': 'off',
    'sort-imports': ['error', {
      'ignoreCase': false,
      'ignoreMemberSort': false,
      'memberSyntaxSortOrder': ['none', 'all', 'single', 'multiple']
    }],
    strict: 'off',
    'valid-jsdoc': 'error',
    'vars-on-top': 'error',
    yoda: 'off',
    'wrap-iife': 'off',
    'wrap-regex': 'error'
  }
}
